packages:
  - .

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - '@vanduo-oss/*'

allowBuilds:
  esbuild: true
  '@vanduo-oss/vdl-cbun@https://codeload.github.com/vanduo-oss/vdl-cbun/tar.gz/ec67960defcaba2869333e22690254e85f70fdc5': true
